@hostname = localhost
@port = 6001
@host = {{hostname}}:{{port}}
@contentType = application/json
@workflowID = BANK_TRANSFER-1709621325

### Get accounts

GET http://{{host}}/accounts
Content-Type: {{contentType}}


### Get balance

POST http://{{host}}/accounts/54892431-0a67-4b66-91c7-255d2321b224/balance
Content-Type: {{contentType}}

{
  "workflow_id": "{{workflowID}}",
  "activity-id": "CHECK_BALANCE",
}