@hostname = localhost
@port = 3131
@host = {{hostname}}:{{port}}
@contentType = application/json

@workflowID = TRANSFER-1708335220

### Create transfer

POST http://{{host}}/transfers
Content-Type: {{contentType}}

{
  "ProductId": 1,
  "Quantity": 1
}


### Add a item

PUT http://{{host}}/transfers/{{workflowID}}/add
Content-Type: {{contentType}}

{
  "ProductId": 1,
  "Quantity": 1
}

### Remove a item

PUT http://{{host}}/transfers/{{workflowID}}/remove
Content-Type: {{contentType}}

{
  "ProductId": 1,
  "Quantity": 1
}

### Checkout

PUT http://{{host}}/transfers/{{workflowID}}/checkout
Content-Type: {{contentType}}

{
  "Email": "test@gmail.com"
}

### Send to email

PUT http://{{host}}/transfers/{{workflowID}}/email
Content-Type: {{contentType}}

{
  "Email": "test@gmail.com"
}
