@hostname = localhost
@port = 3131
@host = {{hostname}}:{{port}}
@contentType = application/json

@workflowID = BANK_TRANSFER-1708491144

### Create transfer

POST http://{{host}}/verifications/otp
Content-Type: {{contentType}}

{
  "token": "token",
  "code": "code",
  "flow_id": "{{workflowID}}",
  "trace": "trace"
}